version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: library_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: library_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # Connection String สำหรับ MongoDB
      MONGO_URI: mongodb://db:27017/library_system
      JWT_SECRET: MySuperSecretKey123
      PORT: 3000
    restart: on-failure

volumes:
  mongo_data: